### ISSUE TITLE
New user added duplicates started user process if they change their slack name

### ISSUE THREAD

**Issue by mgwidmann** [mgwidmann/slack_coder#4]
A user who has the same github and same slack names has no issues. However, when first registering with the system the user is created in the DB and redirected to the edit page (and the user process is started) however, when their slack name is changed the old process is not shut down and new one correctly started up.

**Comment by OkayItsMikael** [comment]
Adding your note from my PR here for reference:
"Make a save [function in UserService] like we have in other services so that we can check if changeset.changes[:slack] || changeset.changes[:github] is changed, and if so make sure to shutdown the user before saving (and then start after saving)."

**Comment by OkayItsMikael** [comment]
🎉
